### ISSUE TITLE
ERROR PageStats plugin : Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by awrog** [francodacosta/grav-plugin-page-stats#32]
Since september 2022 the following error appears in my GRAV log
Sometimes several times a day, sometimes it skips a view days.

[2022-12-29 22:07:11] grav.ERROR: PageStats plugin : Undefined index: HTTP_USER_AGENT - File: /home/.../public_html/user/plugins/page-stats/classes/Stats.php - Line: 85 - Trace: #0 /home/.../public_html/system/src/Grav/Common/Debugger.php(843): Whoops\Run->handleError() #1 /home/.../public_html/user/plugins/page-stats/classes/Stats.php(85): Grav\Common\Debugger->deprecatedErrorHandler() #2 /home/.../public_html/user/plugins/page-stats/classes/Stats.php(127): Grav\Plugin\PageStats\Stats->isBot() #3 /home/.../public_html/user/plugins/page-stats/page-stats.php(216): Grav\Plugin\PageStats\Stats->collect() #4 /home/.../public_html/user/plugins/page-stats/page-stats.php(309): Grav\Plugin\PageStatsPlugin->collectPageData() #5 /home/.../public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\PageStatsPlugin->onPageInitialized() #6 /home/.../public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #7 /home/.../public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #8 /home/.../public_html/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #9 /home/.../public_html/system/src/Grav/Common/Processors/PagesProcessor.php(59): Grav\Common\Grav->fireEvent() #10 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process() #11 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #12 /home/.../public_html/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() #13 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process() #14 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #15 /home/.../public_html/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #16 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process() #17 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #18 /home/.../public_html/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #19 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process() #20 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #21 /home/.../public_html/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #22 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process() #23 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #24 /home/.../public_html/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() #25 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process() #26 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #27 /home/.../public_html/system/src/Grav/Common/Processors/RequestProcessor.php(64): Grav\Framework\RequestHandler\RequestHandler->handle() #28 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process() #29 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #30 /home/.../public_html/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() #31 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process() #32 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #33 /home/.../public_html/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #34 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() #35 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #36 /home/.../public_html/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() #37 /home/.../public_html/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #38 /home/.../public_html/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile() #39 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() #40 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #41 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #42 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() #43 /home/.../public_html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #44 /home/.../public_html/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() #45 /home/.../public_html/index.php(47): Grav\Common\Grav->process() #46 {main} [] []

**Comment by francodacosta** [comment]
@awrog thanks for reporting that, you should get no more warnings about that
